import React, { createContext, useState } from 'react'


export const Store=createContext()
export const Storing = (props) => {
   const [data,setData]=useState([
    {
      id:"1",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"2",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"3",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"4",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"5",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"6",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"7",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"8",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"9",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"10",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"11",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"12",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"13",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"14",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"15",
      cat:"Bollywood",
      bolly_img:"",
      name:"",
      story:""
    },
    {
      id:"16",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"17",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"18",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"19",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"20",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"21",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"22",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"23",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"24",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"25",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"26",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"27",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"28",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"29",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    {
      id:"30",
      cat:"Hollywood",
      holly_img:"",
      name:"",
      story:""
    },
    
    {
      id:"31",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"32",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"33",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"34",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"35",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"36",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"37",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"38",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"39",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"40",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"41",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"42",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"43",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"44",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"45",
      cat:"Tech",
      tech_img:"",
      name:"",
      story:""
    },
    {
      id:"46",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"47",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"48",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"49",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"50",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"51",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"52",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"53",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"54",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"55",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"56",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"57",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"58",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"59",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    {
      id:"60",
      cat:"Food",
      Food_img:"",
      name:"",
      story:""
    },
    
   ])


  return (
    <Store.Provider value={[data,setData]}>
      {props.children}
    </Store.Provider>
  )
}
